### ISSUE TITLE
Is development dead again?

### ISSUE THREAD

**Issue by lastweakness** [Tunous/Dank#27]
Seeing as how there have been no commits this month, is this project dead again?

**Comment by Tunous** [comment]
I would say that it didn't even really resume properly.  For the development to restart it would need someone willing to take the primary development and management role and figure out how to handle releases to play store.

Personally I considered it at first, but then decided that it's not a good idea for me to do that because I'm more of a casual Reddit user. After my few changes and fixes Dank basically reached a state where **for me** it no longer crashes and provides like 90% of functionality I want or use. That's why the commits stopped.

**Comment by lastweakness** [comment]
Ah that makes sense. As a reddit viewer, it does do it's job

**Comment by lastweakness** [comment]
Maybe just build a release and make it the last one until someone else picks it up?

**Comment by Tunous** [comment]
Ok, I've created a release in this repo with latest debug apk: https://github.com/Tunous/Dank/releases/tag/0.6.2-debug

**Comment by lastweakness** [comment]
Great! Thanks for making it stable enough to use
